<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10304" started-at="2022-03-26T07:34:42 IST" finished-at="2022-03-26T07:34:53 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10304" started-at="2022-03-26T07:34:42 IST" finished-at="2022-03-26T07:34:53 IST">
      <class name="Module1_Login_Test.KiteLoginTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8]" name="openBrowser" is-config="true" duration-ms="3679" started-at="2022-03-26T07:34:42 IST" finished-at="2022-03-26T07:34:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="loginToApp()[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8]" name="loginToApp" is-config="true" duration-ms="757" started-at="2022-03-26T07:34:46 IST" finished-at="2022-03-26T07:34:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method status="FAIL" signature="verifyUserID()[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8]" name="verifyUserID" duration-ms="1624" started-at="2022-03-26T07:34:47 IST" finished-at="2022-03-26T07:34:48 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: both results are diff expected [812073] but found [THM944]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: both results are diff expected [812073] but found [THM944]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Module1_Login_Test.KiteLoginTest.verifyUserID(KiteLoginTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserID -->
        <test-method status="PASS" signature="logoutFromApp(org.testng.ITestResult)[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8]" name="logoutFromApp" is-config="true" duration-ms="153" started-at="2022-03-26T07:34:48 IST" finished-at="2022-03-26T07:34:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUserID status=FAILURE method=KiteLoginTest.verifyUserID()[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Module1_Login_Test.KiteLoginTest@23d2a7e8]" name="closeBrowser" is-config="true" duration-ms="4067" started-at="2022-03-26T07:34:48 IST" finished-at="2022-03-26T07:34:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Module1_Login_Test.KiteLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
